name: Docker Image CI
on:
  push:
    branches: [ "main" , "build-docker-image"]
  pull_request:
    branches: [ "main", "build-docker-image" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: petstore
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pet-store-backend:$(date +%s)
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DB_URL: "jdbc:postgresql://postgres:5432/petstore"
          # The default PostgreSQL port
          DB_USER_NAME: "postgres"
          DB_PASSWORD: "postgres"
